### ISSUE TITLE
onItemTap exception

### ISSUE THREAD

**Issue by ProerMo** [embraceitmobile/animated_tree_view#9]
hey bro,I set onItemTap listener,it not works and got exception,maybe you use wrong data in that line.
https://github.com/embraceitmobile/animated_tree_view/blob/e119367211371e6cc5fc804df73d3fa9213a0d55/lib/tree_view/expandable_node.dart#L93

my exception 
```
E/flutter ( 6743): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: type 'TreeNode<BusinessTreeNode<dynamic>>' is not a subtype of type 'BusinessTreeNode<dynamic>'
E/flutter ( 6743): #0      ExpandableNodeItem.build.<anonymous closure> (package:animated_tree_view/tree_view/expandable_node.dart:51:49)
E/flutter ( 6743): #1      _ExpandableNodeContainer.build.<anonymous closure> (package:animated_tree_view/tree_view/expandable_node.dart:93:51)
E/flutter ( 6743): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:253:24)
E/flutter ( 6743): #3      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:627:11)
E/flutter ( 6743): #4      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:306:5)
```

**Comment by jawwad-hassan89** [comment]
Hi bro, yes you are correct, this is a bug due to type mismatch in the onTap callback. I will fix it with my next update in a couple of days.

**Comment by ProerMo** [comment]
thanks
